// Auto-generated by EnumBuilderForStatsIntrinsic.cs on 6/28/2025 2:06:46 AM
// Based on IntrinsicSchemaObject assets found in StatSettings.
// Total items found: 14

// Auto-generated by EnumBuilderForStatsIntrinsic.cs on 6/28/2025 4:13:36 PM
// Based on IntrinsicSchemaObject assets found in StatSettings.
// Total items found: 15

using System;
using System.Runtime.CompilerServices;
using Unity.Burst;
using BovineLabs.Stats.Data;

namespace _src.Scripts.StatsHelpers.StatsHelpers.Data
{
    public enum EIntrinsic : byte
    {
        NullIntrinsic = 0, // From: Null Intrinsic, GUID Prefix: bebe
        Health = 1, // From: 1 Health, GUID Prefix: 18f1
        Xp = 2, // From: 2 Xp, GUID Prefix: 4cbd
        Money = 3, // From: 3 Money, GUID Prefix: 10c3
        Weight = 4, // From: 4 Weight, GUID Prefix: 5ada
        MetroCoin = 5, // From: 5 MetroCoin, GUID Prefix: c052
        Star = 6, // From: 6 Star, GUID Prefix: 0153
        BoostTime = 7, // From: 7 Boost Time, GUID Prefix: bba9
        CollectedItem = 8, // From: 8 Collected Item, GUID Prefix: 8f49
        CollectedPowerUps = 9, // From: 9 Collected PowerUps, GUID Prefix: 01c7
        DetectedCount = 10, // From: 10 Detected Count, GUID Prefix: 1347
        PerformedJump = 11, // From: 11 Performed Jump, GUID Prefix: 3d3e
        PerformedSlide = 12, // From: 12 Performed Slide, GUID Prefix: 7780
        OffsetSide = 13, // From: 13 Offset Side, GUID Prefix: be6b
        OffsetHeight = 14, // From: 14 Offset Height, GUID Prefix: 6448
    }

    
    public static class EIntrinsicExt
    {
        public static string GetGuid(this EIntrinsic item)
        {
            return item switch
            {
                EIntrinsic.NullIntrinsic => "bebe",
                EIntrinsic.Health => "18f1",
                EIntrinsic.Xp => "4cbd",
                EIntrinsic.Money => "10c3",
                EIntrinsic.Weight => "5ada",
                EIntrinsic.MetroCoin => "c052",
                EIntrinsic.Star => "0153",
                EIntrinsic.BoostTime => "bba9",
                EIntrinsic.CollectedItem => "8f49",
                EIntrinsic.CollectedPowerUps => "01c7",
                EIntrinsic.DetectedCount => "1347",
                EIntrinsic.PerformedJump => "3d3e",
                EIntrinsic.PerformedSlide => "7780",
                EIntrinsic.OffsetSide => "be6b",
                EIntrinsic.OffsetHeight => "6448",
                _ => throw new ArgumentOutOfRangeException(nameof(item), item, null)
            };
        }

        public static string ToName(this EIntrinsic item)
        {
            return item switch
            {
                EIntrinsic.NullIntrinsic => "Null Intrinsic",
                EIntrinsic.Health => "Health",
                EIntrinsic.Xp => "Xp",
                EIntrinsic.Money => "Money",
                EIntrinsic.Weight => "Weight",
                EIntrinsic.MetroCoin => "MetroCoin",
                EIntrinsic.Star => "Star",
                EIntrinsic.BoostTime => "Boost Time",
                EIntrinsic.CollectedItem => "Collected Item",
                EIntrinsic.CollectedPowerUps => "Collected PowerUps",
                EIntrinsic.DetectedCount => "Detected Count",
                EIntrinsic.PerformedJump => "Performed Jump",
                EIntrinsic.PerformedSlide => "Performed Slide",
                EIntrinsic.OffsetSide => "Offset Side",
                EIntrinsic.OffsetHeight => "Offset Height",
                _ => throw new ArgumentOutOfRangeException(nameof(item), item, null)
            };
        }

        public static EIntrinsic FromGuid(string guid4)
        {
            if (guid4 == null || guid4.Length != 4)
                throw new ArgumentException($"GUID must be 4 characters long.", nameof(guid4));

            return guid4 switch
            {
                "bebe" => EIntrinsic.NullIntrinsic,
                "18f1" => EIntrinsic.Health,
                "4cbd" => EIntrinsic.Xp,
                "10c3" => EIntrinsic.Money,
                "5ada" => EIntrinsic.Weight,
                "c052" => EIntrinsic.MetroCoin,
                "0153" => EIntrinsic.Star,
                "bba9" => EIntrinsic.BoostTime,
                "8f49" => EIntrinsic.CollectedItem,
                "01c7" => EIntrinsic.CollectedPowerUps,
                "1347" => EIntrinsic.DetectedCount,
                "3d3e" => EIntrinsic.PerformedJump,
                "7780" => EIntrinsic.PerformedSlide,
                "be6b" => EIntrinsic.OffsetSide,
                "6448" => EIntrinsic.OffsetHeight,
                _ => throw new ArgumentOutOfRangeException(nameof(guid4), guid4, null)
            };
        }

        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static IntrinsicKey ToKey(this EIntrinsic intrinsic)
        {
            return new IntrinsicKey { Value = (ushort)intrinsic };
        }
    }
}