// Auto-generated by EnumBuilderForStatsIntrinsic.cs on 6/28/2025 4:11:09 PM
// Based on StatSchemaObject assets found in StatSettings.
// Total items found: 12

using System;
using System.Runtime.CompilerServices;
using Unity.Burst;
using BovineLabs.Stats.Data;

namespace _src.Scripts.StatsHelpers.StatsHelpers.Data
{
    public enum EStat : byte
    {
        NullStat = 0, // From: Null Stat, GUID Prefix: f2a5
        MaxHealth = 1, // From: 1 Max Health, GUID Prefix: be91
        GainRateXp = 2, // From: 2 GainRate Xp, GUID Prefix: 4fe3
        JumpForce = 3, // From: 3 JumpForce, GUID Prefix: f15b
        DetectionRangeSq = 4, // From: 4 Detection Range Sq, GUID Prefix: 11d4
        CollectRangeSq = 5, // From: 5 Collect Range Sq, GUID Prefix: a7d9
        NormalSpeed = 6, // From: 6 Normal Speed, GUID Prefix: 4d7c
        BoostSpeed = 7, // From: 7 Boost Speed, GUID Prefix: c240
        MaxBoostTime = 8, // From: 8 Max Boost Time, GUID Prefix: 6e37
        GainRateBoost = 9, // From: 9 GainRate Boost, GUID Prefix: 829a
        MaxWeight = 10, // From: 10 Max Weight, GUID Prefix: 4509
        LineSwitchSpeed = 11, // From: 11 Line Switch Speed, GUID Prefix: 1ce3
    }

    
    public static class EStatExt
    {
        public static string GetGuid(this EStat item)
        {
            return item switch
            {
                EStat.NullStat => "f2a5",
                EStat.MaxHealth => "be91",
                EStat.GainRateXp => "4fe3",
                EStat.JumpForce => "f15b",
                EStat.DetectionRangeSq => "11d4",
                EStat.CollectRangeSq => "a7d9",
                EStat.NormalSpeed => "4d7c",
                EStat.BoostSpeed => "c240",
                EStat.MaxBoostTime => "6e37",
                EStat.GainRateBoost => "829a",
                EStat.MaxWeight => "4509",
                EStat.LineSwitchSpeed => "1ce3",
                _ => throw new ArgumentOutOfRangeException(nameof(item), item, null)
            };
        }

        public static string ToName(this EStat item)
        {
            return item switch
            {
                EStat.NullStat => "Null Stat",
                EStat.MaxHealth => "Max Health",
                EStat.GainRateXp => "GainRate Xp",
                EStat.JumpForce => "JumpForce",
                EStat.DetectionRangeSq => "Detection Range Sq",
                EStat.CollectRangeSq => "Collect Range Sq",
                EStat.NormalSpeed => "Normal Speed",
                EStat.BoostSpeed => "Boost Speed",
                EStat.MaxBoostTime => "Max Boost Time",
                EStat.GainRateBoost => "GainRate Boost",
                EStat.MaxWeight => "Max Weight",
                EStat.LineSwitchSpeed => "Line Switch Speed",
                _ => throw new ArgumentOutOfRangeException(nameof(item), item, null)
            };
        }

        public static EStat FromGuid(string guid4)
        {
            if (guid4 == null || guid4.Length != 4)
                throw new ArgumentException($"GUID must be 4 characters long.", nameof(guid4));

            return guid4 switch
            {
                "f2a5" => EStat.NullStat,
                "be91" => EStat.MaxHealth,
                "4fe3" => EStat.GainRateXp,
                "f15b" => EStat.JumpForce,
                "11d4" => EStat.DetectionRangeSq,
                "a7d9" => EStat.CollectRangeSq,
                "4d7c" => EStat.NormalSpeed,
                "c240" => EStat.BoostSpeed,
                "6e37" => EStat.MaxBoostTime,
                "829a" => EStat.GainRateBoost,
                "4509" => EStat.MaxWeight,
                "1ce3" => EStat.LineSwitchSpeed,
                _ => throw new ArgumentOutOfRangeException(nameof(guid4), guid4, null)
            };
        }

        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatKey ToKey(this EStat stat)
        {
            return new StatKey { Value = (ushort)stat };
        }
    }
}