// Auto-generated by EnumBuilderForStatsIntrinsic.cs on 7/13/2025 3:27:56 AM
// Based on StatSchemaObject assets found in StatSettings.
// Total items found: 7

using System;
using System.Runtime.CompilerServices;
using BovineLabs.Stats.Data;

public enum EStat : byte
{
    NullStatSchemaObject = 0, // From: NullStatSchemaObject, GUID Prefix: 4d21
    GroundMaxSpeed = 1, // From: 1 Ground Max Speed, GUID Prefix: 2563
    GroundSprintMaxSpeed = 2, // From: 2 Ground Sprint Max Speed, GUID Prefix: 0968
    CrouchedMaxSpeed = 3, // From: 3 Crouched Max Speed, GUID Prefix: b21d
    LedgeMoveSpeed = 4, // From: 4 Ledge Move Speed, GUID Prefix: 238b
    SwimmingMaxSpeed = 5, // From: 5 Swimming Max Speed, GUID Prefix: 13e4
    ClimbingMaxSpeed = 6, // From: 6 Climbing Max Speed, GUID Prefix: 05a2
}

public static class EStatExt
{
    public static string GetGuid(this EStat item)
    {
        return item switch
        {
            EStat.NullStatSchemaObject => "4d21",
            EStat.GroundMaxSpeed => "2563",
            EStat.GroundSprintMaxSpeed => "0968",
            EStat.CrouchedMaxSpeed => "b21d",
            EStat.LedgeMoveSpeed => "238b",
            EStat.SwimmingMaxSpeed => "13e4",
            EStat.ClimbingMaxSpeed => "05a2",
            _ => throw new ArgumentOutOfRangeException(nameof(item), item, null)
        };
    }

    public static string ToName(this EStat item)
    {
        return item switch
        {
            EStat.NullStatSchemaObject => "NullStatSchemaObject",
            EStat.GroundMaxSpeed => "Ground Max Speed",
            EStat.GroundSprintMaxSpeed => "Ground Sprint Max Speed",
            EStat.CrouchedMaxSpeed => "Crouched Max Speed",
            EStat.LedgeMoveSpeed => "Ledge Move Speed",
            EStat.SwimmingMaxSpeed => "Swimming Max Speed",
            EStat.ClimbingMaxSpeed => "Climbing Max Speed",
            _ => throw new ArgumentOutOfRangeException(nameof(item), item, null)
        };
    }

    public static EStat FromGuid(string guid4)
    {
        if (guid4 == null || guid4.Length != 4)
            throw new ArgumentException($"GUID must be 4 characters long.", nameof(guid4));

        return guid4 switch
        {
            "4d21" => EStat.NullStatSchemaObject,
            "2563" => EStat.GroundMaxSpeed,
            "0968" => EStat.GroundSprintMaxSpeed,
            "b21d" => EStat.CrouchedMaxSpeed,
            "238b" => EStat.LedgeMoveSpeed,
            "13e4" => EStat.SwimmingMaxSpeed,
            "05a2" => EStat.ClimbingMaxSpeed,
            _ => throw new ArgumentOutOfRangeException(nameof(guid4), guid4, null)
        };
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static StatKey ToKey(this EStat stat)
    {
        return new StatKey { Value = (ushort)stat };
    }
}