// Auto-generated by EnumBuilderForStatsIntrinsic.cs on 7/12/2025 10:18:03 AM
// Based on StatSchemaObject assets found in StatSettings.
// Total items found: 6

using System;
using System.Runtime.CompilerServices;
using BovineLabs.Stats.Data;

namespace StatsHelpers.StatsHelpers.Data
{
    public enum EStat : byte
    {
        NullStatSchemaObject = 0, // From: NullStatSchemaObject, GUID Prefix: 4d21
        GroundSprintMaxSpeed = 1, // From: 1. Ground Sprint Max Speed, GUID Prefix: 2563
        ClimbingSpeed = 2, // From: 2. Climbing Speed, GUID Prefix: 0968
        CrouchedMaxSpeed = 3, // From: 3. Crouched Max Speed, GUID Prefix: b21d
        LedgeMoveSpeed = 4, // From: 4. Ledge Move Speed, GUID Prefix: 238b
        SwimmingMaxSpeed = 5, // From: 5. Swimming Max Speed, GUID Prefix: 13e4
    }

    public static class EStatExt
    {
        public static string GetGuid(this EStat item)
        {
            return item switch
            {
                EStat.NullStatSchemaObject => "4d21",
                EStat.GroundSprintMaxSpeed => "2563",
                EStat.ClimbingSpeed => "0968",
                EStat.CrouchedMaxSpeed => "b21d",
                EStat.LedgeMoveSpeed => "238b",
                EStat.SwimmingMaxSpeed => "13e4",
                _ => throw new ArgumentOutOfRangeException(nameof(item), item, null)
            };
        }

        public static string ToName(this EStat item)
        {
            return item switch
            {
                EStat.NullStatSchemaObject => "NullStatSchemaObject",
                EStat.GroundSprintMaxSpeed => ". Ground Sprint Max Speed",
                EStat.ClimbingSpeed => ". Climbing Speed",
                EStat.CrouchedMaxSpeed => ". Crouched Max Speed",
                EStat.LedgeMoveSpeed => ". Ledge Move Speed",
                EStat.SwimmingMaxSpeed => ". Swimming Max Speed",
                _ => throw new ArgumentOutOfRangeException(nameof(item), item, null)
            };
        }

        public static EStat FromGuid(string guid4)
        {
            if (guid4 == null || guid4.Length != 4)
                throw new ArgumentException($"GUID must be 4 characters long.", nameof(guid4));

            return guid4 switch
            {
                "4d21" => EStat.NullStatSchemaObject,
                "2563" => EStat.GroundSprintMaxSpeed,
                "0968" => EStat.ClimbingSpeed,
                "b21d" => EStat.CrouchedMaxSpeed,
                "238b" => EStat.LedgeMoveSpeed,
                "13e4" => EStat.SwimmingMaxSpeed,
                _ => throw new ArgumentOutOfRangeException(nameof(guid4), guid4, null)
            };
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static StatKey ToKey(this EStat stat)
        {
            return new StatKey { Value = (ushort)stat };
        }
    }
}